### ISSUE TITLE
To install on Windows

### ISSUE THREAD

**Issue by armine105** [iago-suarez/ELSED#12]
Hello
How are you?
Thanks for contributing to this project.
I am going to use this method on Windows (Win10, x64)anaconda environment.
While installing this, I met the following issue.

(base) E:\tmp\ELSED>python setup.py install
running install
running bdist_egg
running egg_info
writing pyelsed.egg-info\PKG-INFO
writing dependency_links to pyelsed.egg-info\dependency_links.txt
writing top-level names to pyelsed.egg-info\top_level.txt
reading manifest file 'pyelsed.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*' under directory 'pybind11'
adding license file 'LICENSE'
writing manifest file 'pyelsed.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_ext
['cmake', 'E:\\tmp\\ELSED', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=E:\\tmp\\ELSED\\build\\lib.win-amd64-3.9', '-DPYTHON_EXECUTABLE=C:\\Users\\admin\\anaconda3\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=E:\\tmp\\ELSED\\build\\lib.win-amd64-3.9', '-A', 'x64']
CMake Error: The current CMakeCache.txt directory E:/tmp/ELSED/build/temp.win-amd64-3.9/Release/CMakeCache.txt is different than the directory e:/admin/Internet_Task/Jobs/2023/2023.05.15-PoolBallDetection/work/ELSED/build/temp.win-amd64-3.9/Release where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
CMake Error: The source "E:/tmp/ELSED/CMakeLists.txt" does not match the source "E:/admin/Internet_Task/Jobs/2023/2023.05.15-PoolBallDetection/work/ELSED/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.
Traceback (most recent call last):
  File "E:\tmp\ELSED\setup.py", line 63, in <module>
    setup(
  File "C:\Users\admin\anaconda3\lib\site-packages\setuptools\__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\admin\anaconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\admin\anaconda3\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\admin\anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\admin\anaconda3\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\Users\admin\anaconda3\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Users\admin\anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\admin\anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\admin\anaconda3\lib\site-packages\setuptools\command\bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\Users\admin\anaconda3\lib\site-packages\setuptools\command\bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "C:\Users\admin\anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\admin\anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\admin\anaconda3\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "C:\Users\admin\anaconda3\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "C:\Users\admin\anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\admin\anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "E:\tmp\ELSED\setup.py", line 32, in run
    self.build_extension(ext)
  File "E:\tmp\ELSED\setup.py", line 59, in build_extension
    subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
  File "C:\Users\admin\anaconda3\lib\subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', 'E:\\tmp\\ELSED', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=E:\\tmp\\ELSED\\build\\lib.win-amd64-3.9', '-DPYTHON_EXECUTABLE=C:\\Users\\admin\\anaconda3\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=E:\\tmp\\ELSED\\build\\lib.win-amd64-3.9', '-A', 'x64']' returned non-zero exit status 1.

**Comment by armine105** [comment]
I could build & install this lib.
But when I import this lib in python, I meet the following issue.

Traceback (most recent call last):
  File "E:\admin\Internet_Task\Jobs\2023\2023.05.15-PoolBallDetection\work\ELSED\demo.py", line 1, in <module>
    import pyelsed
ImportError: DLL load failed while importing pyelsed: The specified module could not be found.
